### ISSUE TITLE
turn off mozbot notifications for not-develop/not-master branches?

### ISSUE THREAD

**Issue by Pomax** [cadecairos/mozbot#2]
Mozbot currently reports on all activity on our repos, including feature branch pushes that have no direct meaning to the master or develop branches (such as feature branches etc). It would be nice if activity on these branches is not reported on in mattermost.

**Comment by cadecairos** [comment]
this should be a simple check in the hook code

``` coffeescript
return if foo.blah not in ['develop', 'master']
```

**Comment by cadecairos** [comment]
@Pomax care to R? that PR? :)
